// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TeamSelectorController from "./team_selector_controller"
application.register("team-selector", TeamSelectorController)

import WorkDurationController from "./work_duration_controller"
application.register("work-duration", WorkDurationController)

import SearchFilterController from "./search_filter_controller"
application.register("search-filter", SearchFilterController)